sudo: required

services:
  - docker

before_install:
  - docker pull xjodoin/hugo

script:
  - docker run -v $(pwd):$(pwd) -w $(pwd) xjodoin/hugo
  - docker build -t xjodoin/xavier .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push xjodoin/xavier;
    fi
